# Generated by Django 2.0.2 on 2018-03-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcamimages',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
