# Generated by Django 2.0.2 on 2018-03-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180303_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcamimages',
            name='grayscale',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
